import io.rizvan.beans.KnowledgeInferredSignal
import io.rizvan.beans.actors.Agent
import io.rizvan.beans.knowledge.AgentKnowledge
import io.rizvan.beans.knowledge.AgentPossibilities
import io.rizvan.beans.GameState
import io.rizvan.beans.knowledge.PlayerIsCloseSignal

rule "Agent collect points"
agenda-group "agent-choices-group"
no-loop true
    when
        $agent : Agent($agentX : getX(), $agentY : getY())
        $knowledge : AgentKnowledge($timeLeft : getTimeLeft(), $playerIsClose : isPlayerClose($agentX, $agentY))
        $possibilities : AgentPossibilities($worthCollectingPoints : canWinByPointCollection(), $playerCanKill : isKilledByPlayer())
        eval($timeLeft > GameState.GAME_TIME * 0.50 && !$playerCanKill && !$playerIsClose)
        eval(($timeLeft <= GameState.GAME_TIME * 0.50 && $timeLeft > GameState.GAME_TIME * 0.35) && $worthCollectingPoints)
        eval($timeLeft <= GameState.GAME_TIME * 0.10 && $worthCollectingPoints && (!$playerCanKill || !$playerIsClose))
    then
        System.out.println("Agent collect points - ran");
end

rule "Agent avoid player"
agenda-group "agent-choices-group"
no-loop true
    when
        $knowledge : AgentKnowledge($timeLeft : getTimeLeft())
        $possibilities : AgentPossibilities(
                            $agentCanKill : canKillPlayer(),
                            $agentOneShots : canOneShootPlayer(),
                            $playerCanKill : isKilledByPlayer(),
                            $playerOneShots : isOneShotByPlayer(),
                            $worthCollectingPoints : canWinByPointCollection()
                         )
        eval($playerCanKill && $playerOneShots && $timeLeft <= GameState.GAME_TIME * 0.35 || ($timeLeft <= GameState.GAME_TIME * 0.10 && !$agentCanKill))
    then
        System.out.println("Agent avoid player - ran");
end

rule "Agent kill player"
agenda-group "agent-choices-group"
no-loop true
    when
        $knowledge : AgentKnowledge($timeLeft : getTimeLeft())
        $possibilities : AgentPossibilities(
                            $agentCanKill : canKillPlayer(),
                            $agentOneShots : canOneShootPlayer(),
                            $playerCanKill : isKilledByPlayer() == false,
                            $playerOneShots : isOneShotByPlayer() == false,
                            $worthCollectingPoints : canWinByPointCollection() == false
                         )
        eval(($timeLeft <= GameState.GAME_TIME * 0.50 && $agentOneShots && !$playerOneShots) ||
             ($timeLeft <= GameState.GAME_TIME * 0.35 && $agentCanKill) ||
             ($timeLeft <= GameState.GAME_TIME * 0.10 && $agentCanKill))
    then
        System.out.println("Agent kill player - ran");
end