package rules

import io.rizvan.beans.Facts.GameTimeChangeFact;
import io.rizvan.beans.Facts.PlayerMovementFact;
import io.rizvan.beans.Facts.PlayerAimFact;
import io.rizvan.beans.actors.Agent;

rule "Player Movement Fact"
    when
        $agent: Agent()
        $playerMoveFact : PlayerMovementFact()
    then
        System.out.println("Player moved to position x: " + $playerMoveFact.getX()
            + " y: " + $playerMoveFact.getY());
end

rule "Player Aiming Fact"
    when
        $agent: Agent()
        $aimFact : PlayerAimFact()
    then
        System.out.println("Mouse x: " + $aimFact.getMouseX() + "Mouse y: " + $aimFact.getMouseY());
end