title: Game Of Points
markdown: kramdown
remote_theme: just-the-docs/just-the-docs

aux_links:
  Just the Docs on GitHub:
    - https://github.com/just-the-docs/just-the-docs

callouts:
  warning:
    title: Warning
    color: red
  tip:
    title: Tip
    color: green
  info:
    title: Info
    color: blue
  note:
    title: Note
    color: yellow

mermaid:
  version: "11.6.0"
