title: Game Of Points
markdown: kramdown
remote_theme: just-the-docs/just-the-docs

callouts:
  warning:
    title: Warning
    color: red
  tip:
    title: Tip
    color: green
  info:
    title: Info
    color: blue
  note:
    title: Note
    color: yellow

mermaid:
  version: "11.6.0"

back_to_top: true
back_to_top_text: "Back to top"

just_the_docs:
  auxiliary_css: "/assets/css/custom.css"
