title: Game Of Points
markdown: kramdown
remote_theme: just-the-docs/just-the-docs

callouts:
  warning:
    title: Warning
    color: red
  tip:
    title: Tip
    color: green
  info:
    title: Info
    color: blue
  note:
    title: Note
    color: yellow